name: Android CI

on:
  push:
    branches: [ "**" ] # run ci pipeline on any commit pushed on any branch


jobs:
  build: # build job
    runs-on: ubuntu-latest # run our actions on a Ubuntu Host Server of latest version(20.4)

    steps:
      - name: checkout repo
        uses: actions/checkout@v3 # Checkout the commit that triggered the workflow
      - name: set up JDK 11 # Downloading and setting up the requested version of Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Android Lint
        run: ./gradlew lint

      - name: Build with Gradle
        run: ./gradlew build

  test:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK 11 # Downloading and setting up the requested version of Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Unit tests results
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
